apiVersion: v1
kind: Secret
metadata:
  name: {{ template "outline.fullname" . }}
  namespace: {{ template "outline.namespace" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  .env: |-
  {{- range $key, $val := .Values.env }}
    {{ $key }}={{ $val | b64enc | quote }}
  {{- end }}
