apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "outline.fullname" . }}
  namespace: {{ template "outline.namespace" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
